services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: google_api
      POSTGRES_USER: google_api
      POSTGRES_PASSWORD: yp3NVPay
  backend-app:
    build: ./google_api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             (python manage.py runserver 0.0.0.0:8000 &
              python manage.py run_scheduler &
              python manage.py run_bot)"
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend-app:
    build: ./google_api_frontend
    ports:
      - 3000:3000
    depends_on:
      - backend-app
