# Generated by Django 4.1.7 on 2023-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(help_text='Number of the order that contains the item.')),
                ('cost_usd', models.DecimalField(decimal_places=2, help_text='The cost of the item in US dollars.', max_digits=8)),
                ('cost_rub', models.DecimalField(decimal_places=2, help_text='The cost of the item in Russian rubles.', max_digits=8)),
                ('delivery_time', models.DateField(help_text='The date by which the item must be delivered.')),
            ],
        ),
    ]
