# Generated by Django 4.1.7 on 2023-03-21 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='delivery_time',
            new_name='delivery_date',
        ),
    ]
