# Generated by Django 4.1.7 on 2023-03-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_updateexecution_updateexecutionerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateexecution',
            name='usd_exchange_rate',
            field=models.FloatField(blank=True, help_text='USD exchange rate used to calculate cost in USD.', null=True),
        ),
    ]
