# Generated by Django 4.1.7 on 2023-03-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_updateexecution_usd_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateexecution',
            name='document_timestamp',
            field=models.CharField(blank=True, help_text='The information about date and time of document changing.', max_length=30),
        ),
    ]
